import type { Slot } from '../types';

export const formations: Record<string, Slot[]> = {
  '4-3-3': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rb', label: 'TD', position: 'RB', x: 82, y: 73 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 62, y: 76 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 38, y: 76 },
    { id: 'lb', label: 'TS', position: 'LB', x: 18, y: 73 },
    { id: 'dm', label: 'MED', position: 'DM', x: 50, y: 58 },
    { id: 'rcm', label: 'CC', position: 'CM', x: 66, y: 47 },
    { id: 'lcm', label: 'TRQ', position: 'AM', x: 34, y: 47 },
    { id: 'rw', label: 'AD', position: 'RW', x: 82, y: 23 },
    { id: 'st', label: 'ATT', position: 'ST', x: 50, y: 17 },
    { id: 'lw', label: 'AS', position: 'LW', x: 18, y: 23 },
  ],
  '4-2-3-1': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rb', label: 'TD', position: 'RB', x: 82, y: 74 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 62, y: 76 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 38, y: 76 },
    { id: 'lb', label: 'TS', position: 'LB', x: 18, y: 74 },
    { id: 'rdm', label: 'MED', position: 'DM', x: 61, y: 59 },
    { id: 'ldm', label: 'CC', position: 'CM', x: 39, y: 59 },
    { id: 'rw', label: 'AD', position: 'RW', x: 82, y: 43 },
    { id: 'am', label: 'TRQ', position: 'AM', x: 50, y: 40 },
    { id: 'lw', label: 'AS', position: 'LW', x: 18, y: 43 },
    { id: 'st', label: 'ATT', position: 'ST', x: 50, y: 19 },
  ],
  '4-4-2': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rb', label: 'TD', position: 'RB', x: 82, y: 75 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 62, y: 77 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 38, y: 77 },
    { id: 'lb', label: 'TS', position: 'LB', x: 18, y: 75 },
    { id: 'rm', label: 'ED', position: 'RM', x: 82, y: 55 },
    { id: 'rcm', label: 'CC', position: 'CM', x: 60, y: 55 },
    { id: 'lcm', label: 'MED', position: 'DM', x: 40, y: 55 },
    { id: 'lm', label: 'ES', position: 'LM', x: 18, y: 55 },
    { id: 'rst', label: 'ATT', position: 'ST', x: 61, y: 22 },
    { id: 'lst', label: 'ATT', position: 'ST', x: 39, y: 22 },
  ],
  '4-2-4': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rb', label: 'TD', position: 'RB', x: 82, y: 73 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 62, y: 76 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 38, y: 76 },
    { id: 'lb', label: 'TS', position: 'LB', x: 18, y: 73 },
    { id: 'rdm', label: 'MED', position: 'DM', x: 60, y: 56 },
    { id: 'lcm', label: 'CC', position: 'CM', x: 40, y: 56 },
    { id: 'rw', label: 'AD', position: 'RW', x: 88, y: 26 },
    { id: 'rst', label: 'ATT', position: 'ST', x: 62, y: 18 },
    { id: 'lst', label: 'ATT', position: 'ST', x: 38, y: 18 },
    { id: 'lw', label: 'AS', position: 'LW', x: 12, y: 26 },
  ],
  '4-5-1': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rb', label: 'TD', position: 'RB', x: 82, y: 75 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 62, y: 77 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 38, y: 77 },
    { id: 'lb', label: 'TS', position: 'LB', x: 18, y: 75 },
    { id: 'rm', label: 'ED', position: 'RM', x: 86, y: 52 },
    { id: 'rcm', label: 'CC', position: 'CM', x: 65, y: 56 },
    { id: 'dm', label: 'MED', position: 'DM', x: 50, y: 62 },
    { id: 'lam', label: 'TRQ', position: 'AM', x: 35, y: 56 },
    { id: 'lm', label: 'ES', position: 'LM', x: 14, y: 52 },
    { id: 'st', label: 'ATT', position: 'ST', x: 50, y: 20 },
  ],
  '3-5-2': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 70, y: 76 },
    { id: 'cb', label: 'DC', position: 'CB', x: 50, y: 78 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 30, y: 76 },
    { id: 'rm', label: 'ED', position: 'RM', x: 88, y: 51 },
    { id: 'rdm', label: 'MED', position: 'DM', x: 62, y: 57 },
    { id: 'cm', label: 'CC', position: 'CM', x: 50, y: 50 },
    { id: 'lam', label: 'TRQ', position: 'AM', x: 38, y: 57 },
    { id: 'lm', label: 'ES', position: 'LM', x: 12, y: 51 },
    { id: 'rst', label: 'ATT', position: 'ST', x: 61, y: 21 },
    { id: 'lst', label: 'ATT', position: 'ST', x: 39, y: 21 },
  ],
  '5-3-2': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rwb', label: 'TD', position: 'RB', x: 90, y: 70 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 68, y: 77 },
    { id: 'cb', label: 'DC', position: 'CB', x: 50, y: 79 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 32, y: 77 },
    { id: 'lwb', label: 'TS', position: 'LB', x: 10, y: 70 },
    { id: 'rcm', label: 'CC', position: 'CM', x: 64, y: 55 },
    { id: 'dm', label: 'MED', position: 'DM', x: 50, y: 60 },
    { id: 'lam', label: 'TRQ', position: 'AM', x: 36, y: 55 },
    { id: 'rst', label: 'ATT', position: 'ST', x: 61, y: 24 },
    { id: 'lst', label: 'ATT', position: 'ST', x: 39, y: 24 },
  ],
  '3-4-3': [
    { id: 'gk', label: 'POR', position: 'GK', x: 50, y: 89 },
    { id: 'rcb', label: 'DC', position: 'CB', x: 72, y: 77 },
    { id: 'cb', label: 'DC', position: 'CB', x: 50, y: 79 },
    { id: 'lcb', label: 'DC', position: 'CB', x: 28, y: 77 },
    { id: 'rm', label: 'ED', position: 'RM', x: 88, y: 48 },
    { id: 'rcm', label: 'CC', position: 'CM', x: 62, y: 56 },
    { id: 'lcm', label: 'MED', position: 'DM', x: 38, y: 56 },
    { id: 'lm', label: 'ES', position: 'LM', x: 12, y: 48 },
    { id: 'rw', label: 'AD', position: 'RW', x: 82, y: 22 },
    { id: 'st', label: 'ATT', position: 'ST', x: 50, y: 16 },
    { id: 'lw', label: 'AS', position: 'LW', x: 18, y: 22 },
  ],
};

export const defaultFormation = '4-3-3';
